general.import = ["~/.config/alacritty//themes/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 11

[window]
padding.x = 5
padding.y = 5
decorations = "None"
opacity = 1.00

[keyboard]
# bindings = [{ key = "F11", action = "ToggleFullscreen" }]
