# Catppuccin Latte 主题 - Rio Terminal (亮色主题)
[colors]
background = "#eff1f5"
foreground = "#4c4f69"
cursor = "#dc8a78"
selection-foreground = "#eff1f5"
selection-background = "#dc8a78"

[colors.normal]
black = "#5c5f77"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#acb0be"

[colors.bright]
black = "#6c6f85"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#bcc0cc"

[colors.dim]
black = "#eff1f5"
red = "#e64553"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#4c4f69"
