# Tokyo Night 主题 - Rio Terminal
[colors]
background = "#1a1b26"
foreground = "#c0caf5"
cursor = "#c0caf5"
selection-foreground = "#c0caf5"
selection-background = "#33467c"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.dim]
black = "#0f0f14"
red = "#d5617f"
green = "#8fb859"
yellow = "#c7975b"
blue = "#6a92e0"
magenta = "#a583e8"
cyan = "#6bb5df"
white = "#9198b5"
