# GitHub Dark 主题 - Rio Terminal
[colors]
background = "#0d1117"
foreground = "#c9d1d9"
cursor = "#c9d1d9"
selection-foreground = "#c9d1d9"
selection-background = "#264f78"

[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#7ce38b"
yellow = "#ffa657"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#a5f3fc"
white = "#f0f6fc"

[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#ffb570"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39d0d6"
white = "#f0f6fc"

[colors.dim]
black = "#21262d"
red = "#f85149"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#a5a2ff"
cyan = "#39c5cf"
white = "#b1bac4"
