# Gruvbox Light 主题 - Rio Terminal
[colors]
background = "#fbf1c7"
foreground = "#3c3836"
cursor = "#3c3836"
selection-foreground = "#3c3836"
selection-background = "#ebdbb2"

[colors.normal]
black = "#fbf1c7"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#7c6f64"

[colors.bright]
black = "#928374"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"

[colors.dim]
black = "#f2e5bc"
red = "#af3a03"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#504945"
