# Tokyo Night Theme for Yazi
# A clean, dark theme inspired by Tokyo cityscape at night
# Based on the popular Tokyo Night VS Code theme

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Tokyo Night Storm Color Palette
# Background colors:
# - bg: #24283b (main background)
# - bg_dark: #1f2335 (darker background)
# - bg_highlight: #292e42 (highlight background)
# - bg_visual: #2e3c64 (visual selection background)
# - bg_sidebar: #1f2335 (sidebar background)
# - bg_float: #1f2335 (floating window background)
# - fg: #c0caf5 (primary text)
# - fg_dark: #a9b1d6 (secondary text)
# - fg_gutter: #3b4261 (gutter text)
# - comment: #565f89 (comments)
# - border: #29a4bd (border color)
# - blue: #7aa2f7 (blue)
# - cyan: #7dcfff (cyan)
# - green: #9ece6a (green)
# - orange: #ff9e64 (orange)
# - red: #f7768e (red)
# - magenta: #bb9af7 (magenta)
# - purple: #9d7cd8 (purple)
# - yellow: #e0af68 (yellow)
# - blue1: #2ac3de (light blue)
# - blue2: #0db9d7 (info blue)
# - green1: #73daca (teal green)
# - red1: #db4b4b (error red)
# - terminal_black: #414868 (terminal black)

# : Manager {{{

[mgr]
cwd = { fg = "#7aa2f7", bold = true } # blue - current directory

# Hovered states
hovered = { bg = "#292e42", bold = true }              # bg_highlight
preview_hovered = { underline = true, fg = "#c0caf5" } # fg

# Find/search
find_keyword = { fg = "#e0af68", bold = true, italic = true, underline = true } # yellow
find_position = { fg = "#bb9af7", bg = "#24283b", bold = true, italic = true }  # magenta on bg

# Symlink
symlink_target = { fg = "#7dcfff", italic = true } # cyan

# Markers
marker_copied = { fg = "#24283b", bg = "#7dcfff" }   # bg on cyan
marker_cut = { fg = "#24283b", bg = "#f7768e" }      # bg on red
marker_marked = { fg = "#24283b", bg = "#bb9af7" }   # bg on magenta
marker_selected = { fg = "#24283b", bg = "#e0af68" } # bg on yellow

# Counts
count_copied = { fg = "#c0caf5", bg = "#7dcfff" }   # fg on cyan
count_cut = { fg = "#c0caf5", bg = "#f7768e" }      # fg on red
count_selected = { fg = "#c0caf5", bg = "#e0af68" } # fg on yellow

# Border
border_symbol = "│"
border_style = { fg = "#29a4bd" } # border for visibility

# Syntax highlighting
syntect_theme = "tmtheme.xml"

# : }}}

# : Tabs {{{

[tabs]
active = { fg = "#c0caf5", bg = "#7aa2f7", bold = true } # fg on blue - active tab
inactive = { fg = "#a9b1d6", bg = "#1f2335" }            # fg_dark on bg_dark - inactive tabs

# Tab separators
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}

# : Mode indicator {{{

[mode]
normal_main = { fg = "#c0caf5", bg = "#7aa2f7", bold = true } # fg on blue
normal_alt = { fg = "#7aa2f7", bg = "#1f2335" }               # blue on bg_dark

select_main = { fg = "#c0caf5", bg = "#f7768e", bold = true } # fg on red  
select_alt = { fg = "#f7768e", bg = "#1f2335" }               # red on bg_dark

unset_main = { fg = "#c0caf5", bg = "#e0af68", bold = true } # fg on yellow
unset_alt = { fg = "#e0af68", bg = "#1f2335" }               # yellow on bg_dark

# : }}}

# : Status bar {{{

[status]
overall = { fg = "#c0caf5", bg = "#24283b" } # fg on bg
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# File permissions
perm_sep = { fg = "#29a4bd" }   # border
perm_type = { fg = "#7aa2f7" }  # blue - file type
perm_read = { fg = "#e0af68" }  # yellow - read permission
perm_write = { fg = "#f7768e" } # red - write permission  
perm_exec = { fg = "#9ece6a" }  # green - execute permission

# Progress indicators
progress_label = { fg = "#c0caf5", bold = true }     # fg - progress label
progress_normal = { fg = "#7aa2f7", bg = "#1f2335" } # blue on bg_dark
progress_error = { fg = "#f7768e", bg = "#1f2335" }  # red on bg_dark

# : }}}

# : Which-key menu {{{

[which]
cols = 3
mask = { bg = "#24283b" }              # bg background
cand = { fg = "#7dcfff", bold = true } # cyan - command candidates
rest = { fg = "#565f89" }              # comment - rest of command
desc = { fg = "#bb9af7" }              # magenta - descriptions
separator = "  "
separator_style = { fg = "#29a4bd" }   # border

# : }}}

# : Confirmation dialog {{{

[confirm]
border = { fg = "#7aa2f7" }                  # blue border
title = { fg = "#7aa2f7", bold = true }      # blue title
content = { fg = "#c0caf5" }                 # fg - dialog content
list = { fg = "#a9b1d6" }                    # fg_dark - item list
btn_yes = { fg = "#24283b", bg = "#9ece6a" } # bg on green - yes button
btn_no = { fg = "#24283b", bg = "#f7768e" }  # bg on red - no button
btn_labels = ["Yes", "No"]                   # button labels

# : }}}

# : File search/spotter {{{

[spot]
border = { fg = "#7aa2f7" }             # blue
title = { fg = "#7aa2f7", bold = true } # blue

# Table view - file search results
tbl_col = { fg = "#7dcfff", bold = true }     # cyan - column headers
tbl_cell = { fg = "#e0af68", bg = "#1f2335" } # yellow on bg_dark

# : }}}

# : Notifications {{{

[notify]
title_info = { fg = "#7aa2f7", bold = true }  # blue - info notifications
title_warn = { fg = "#e0af68", bold = true }  # yellow - warning notifications  
title_error = { fg = "#f7768e", bold = true } # red - error notifications

# : }}}

# : File picker {{{

[pick]
border = { fg = "#7aa2f7" }              # blue
active = { fg = "#bb9af7", bold = true } # magenta - active item
inactive = { fg = "#a9b1d6" }            # fg_dark - inactive items

# : }}}

# : Input field {{{

[input]
border = { fg = "#7aa2f7" }                   # blue
title = { fg = "#7dcfff", bold = true }       # cyan
value = { fg = "#c0caf5" }                    # fg
selected = { fg = "#c0caf5", bg = "#bb9af7" } # fg on magenta

# : }}}

# : Command completion {{{

[cmp]
border = { fg = "#7aa2f7" }                 # blue
active = { fg = "#24283b", bg = "#7dcfff" } # bg on cyan
inactive = { fg = "#a9b1d6" }               # fg_dark

# Completion icons
icon_file = ""    # file icon
icon_folder = ""  # folder icon  
icon_command = "" # command icon

# : }}}

# : Task manager {{{

[tasks]
border = { fg = "#7aa2f7" }                    # blue
title = { fg = "#7dcfff", bold = true }        # cyan
hovered = { fg = "#bb9af7", underline = true } # magenta

# : }}}

# : Help menu {{{

[help]
on = { fg = "#7dcfff", bold = true }                      # cyan - enabled features
run = { fg = "#bb9af7", bold = true }                     # magenta - runnable commands
desc = { fg = "#a9b1d6" }                                 # fg_dark - descriptions
hovered = { fg = "#24283b", bg = "#9d7cd8", bold = true } # bg on purple
footer = { fg = "#24283b", bg = "#c0caf5" }               # bg on fg

# : }}}

# : File type colors {{{

[filetype]
rules = [
    # Images - purple color for visual files
    { mime = "image/*", fg = "#9d7cd8" },

    # Audio/Video - red color for media
    { mime = "audio/*", fg = "#f7768e" },
    { mime = "video/*", fg = "#f7768e" },

    # Archives - orange color for compressed files
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ff9e64" },

    # Documents - blue color for text documents
    { mime = "application/{pdf,doc,rtf,odt,ods,odp}", fg = "#7aa2f7" },
    { mime = "text/*", fg = "#7aa2f7" },

    # Code files - cyan color for source code
    { mime = "application/{javascript,typescript,json,xml}", fg = "#7dcfff" },

    # Special file states
    { name = "*", is = "orphan", bg = "#f7768e", fg = "#c0caf5" }, # red background
    { name = "*", is = "exec", fg = "#e0af68", bold = true },      # yellow for executables

    # Dummy/placeholder files
    { name = "*", is = "dummy", bg = "#565f89", fg = "#c0caf5" },

    # Directories - magenta color
    { name = "*/", fg = "#bb9af7", bold = true },

    # Default fallback
    { name = "*", fg = "#c0caf5" }, # fg color
]

# : }}}

# : Icons {{{

[icon]
globs = []

# Directory icons
dirs = [
    { name = ".git", text = "", fg = "#f7768e" },         # red
    { name = ".github", text = "", fg = "#f7768e" },      # red
    { name = ".config", text = "", fg = "#7aa2f7" },      # blue
    { name = ".npm", text = "", fg = "#f7768e" },         # red
    { name = ".vscode", text = "", fg = "#7aa2f7" },      # blue
    { name = "node_modules", text = "", fg = "#ff9e64" }, # orange
    { name = "Desktop", text = "", fg = "#7dcfff" },      # cyan
    { name = "Documents", text = "", fg = "#7aa2f7" },    # blue
    { name = "Downloads", text = "", fg = "#ff9e64" },    # orange
    { name = "Pictures", text = "", fg = "#9d7cd8" },     # purple
    { name = "Music", text = "", fg = "#f7768e" },        # red
    { name = "Videos", text = "", fg = "#f7768e" },       # red
    { name = "Development", text = "", fg = "#7dcfff" },  # cyan
    { name = "Projects", text = "", fg = "#7dcfff" },     # cyan
]

# File icons
files = [
    # Git files
    { name = ".gitignore", text = "", fg = "#f7768e" },
    { name = ".gitconfig", text = "", fg = "#f7768e" },

    # Config files
    { name = ".bashrc", text = "", fg = "#7aa2f7" },
    { name = ".zshrc", text = "", fg = "#7aa2f7" },
    { name = ".vimrc", text = "", fg = "#7aa2f7" },

    # Web development
    { name = "*.html", text = "", fg = "#f7768e" }, # red
    { name = "*.css", text = "", fg = "#7aa2f7" },  # blue
    { name = "*.scss", text = "", fg = "#9d7cd8" }, # purple
    { name = "*.js", text = "", fg = "#e0af68" },   # yellow
    { name = "*.ts", text = "", fg = "#7aa2f7" },   # blue
    { name = "*.jsx", text = "", fg = "#7dcfff" },  # cyan
    { name = "*.tsx", text = "", fg = "#7dcfff" },  # cyan

    # Programming languages
    { name = "*.py", text = "", fg = "#e0af68" },   # yellow
    { name = "*.rs", text = "", fg = "#f7768e" },   # red
    { name = "*.go", text = "", fg = "#7dcfff" },   # cyan
    { name = "*.cpp", text = "", fg = "#7aa2f7" },  # blue
    { name = "*.c", text = "", fg = "#7aa2f7" },    # blue
    { name = "*.java", text = "", fg = "#ff9e64" }, # orange

    # Data files
    { name = "*.json", text = "", fg = "#e0af68" }, # yellow
    { name = "*.yaml", text = "", fg = "#bb9af7" }, # magenta
    { name = "*.yml", text = "", fg = "#bb9af7" },  # magenta
    { name = "*.toml", text = "", fg = "#bb9af7" }, # magenta

    # Documents
    { name = "*.pdf", text = "", fg = "#f7768e" }, # red
    { name = "*.md", text = "", fg = "#7dcfff" },  # cyan
    { name = "*.txt", text = "", fg = "#c0caf5" }, # fg

    # Images
    { name = "*.png", text = "", fg = "#9d7cd8" }, # purple
    { name = "*.jpg", text = "", fg = "#9d7cd8" }, # purple
    { name = "*.svg", text = "", fg = "#e0af68" }, # yellow

    # Media files
    { name = "*.mp3", text = "", fg = "#f7768e" }, # red
    { name = "*.mp4", text = "", fg = "#f7768e" }, # red

    # Archives
    { name = "*.zip", text = "", fg = "#ff9e64" }, # orange
    { name = "*.tar", text = "", fg = "#ff9e64" }, # orange

    # Special files
    { name = "Dockerfile", text = "", fg = "#7aa2f7" }, # blue
    { name = "Makefile", text = "", fg = "#7dcfff" },   # cyan
    { name = "README.md", text = "", fg = "#e0af68" },  # yellow
]

# Extensions fallback
exts = [
    { name = "py", text = "", fg = "#e0af68" },   # yellow
    { name = "js", text = "", fg = "#e0af68" },   # yellow
    { name = "ts", text = "", fg = "#7aa2f7" },   # blue
    { name = "rs", text = "", fg = "#f7768e" },   # red
    { name = "html", text = "", fg = "#f7768e" }, # red
    { name = "css", text = "", fg = "#7aa2f7" },  # blue
    { name = "png", text = "", fg = "#9d7cd8" },  # purple
    { name = "jpg", text = "", fg = "#9d7cd8" },  # purple
    { name = "*", text = "", fg = "#c0caf5" },    # fg
]

# : }}}
