# Gruvbox Dark 主题 - Rio Terminal
[colors]
background = "#282828"
foreground = "#ebdbb2"
cursor = "#ebdbb2"
selection-foreground = "#ebdbb2"
selection-background = "#3c3836"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.dim]
black = "#1d2021"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#7c6f64"
