# Dracula 主题 - Rio Terminal
[colors]
background = "#282a36"
foreground = "#f8f8f2"
cursor = "#f8f8f2"
selection-foreground = "#ffffff"
selection-background = "#44475a"

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.dim]
black = "#14151b"
red = "#ff2222"
green = "#1ef956"
yellow = "#ebf85b"
blue = "#4d2c91"
magenta = "#ff46b0"
cyan = "#59dffc"
white = "#e6e6d1"
