# Rosé Pine Dawn theme for Rio Terminal
# Based on the official Rosé Pine Dawn color palette: https://rosepinetheme.com/

[colors]
# Background colors
background = '#faf4ed' # Base - Primary background
foreground = '#575279' # Text - High contrast foreground

# Normal colors
black = '#f2e9e1'   # Overlay
red = '#b4637a'     # Love - Per favore ama tutti
green = '#286983'   # Pine - Fresh winter greenery
yellow = '#ea9d34'  # Gold - Lemon tea on a summer morning
blue = '#56949f'    # Foam - Saltwater tidepools
magenta = '#907aa9' # Iris - Smells of groundedness
cyan = '#d7827e'    # Rose - A beautiful yet cautious blossom
white = '#575279'   # Text

# Bright colors
light-black = '#9893a5'   # Muted - Low contrast foreground
light-red = '#b4637a'     # Love
light-green = '#286983'   # Pine
light-yellow = '#ea9d34'  # Gold
light-blue = '#56949f'    # Foam
light-magenta = '#907aa9' # Iris
light-cyan = '#d7827e'    # Rose
light-white = '#575279'   # Text

# Dim colors
dim-black = '#f4ede8'   # Highlight Low
dim-red = '#b4637a'     # Love
dim-green = '#286983'   # Pine
dim-yellow = '#ea9d34'  # Gold
dim-blue = '#56949f'    # Foam
dim-magenta = '#907aa9' # Iris
dim-cyan = '#d7827e'    # Rose
dim-white = '#797593'   # Subtle

# UI colors
cursor = '#cecacd'    # Highlight High
vi-cursor = '#cecacd' # Highlight High

# Selection
selection-foreground = '#575279' # Text
selection-background = '#dfdad9' # Highlight Med

# Search
search-match-background = '#dfdad9'         # Highlight Med
search-match-foreground = '#575279'         # Text
search-focused-match-background = '#cecacd' # Highlight High
search-focused-match-foreground = '#575279' # Text

# Navigation/Tabs
tabs = '#fffaf3'                   # Surface
tabs-foreground = '#797593'        # Subtle
tabs-active = '#f2e9e1'            # Overlay
tabs-active-foreground = '#575279' # Text
tabs-active-highlight = '#907aa9'  # Iris
bar = '#faf4ed'                    # Base
