# Material Dark 主题 - Rio Terminal
[colors]
background = "#263238"
foreground = "#eeffff"
cursor = "#eeffff"
selection-foreground = "#eeffff"
selection-background = "#37474f"

[colors.normal]
black = "#263238"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#eeffff"

[colors.bright]
black = "#546e7a"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#ffffff"

[colors.dim]
black = "#1a1f23"
red = "#d45454"
green = "#a5c261"
yellow = "#ffa726"
blue = "#5f7fd3"
magenta = "#a270ba"
cyan = "#60b4d1"
white = "#b0bec5"
