# Solarized Dark 主题 - Rio Terminal
[colors]
background = "#002b36"
foreground = "#839496"
cursor = "#839496"
selection-foreground = "#93a1a1"
selection-background = "#073642"

[colors.normal]
black = "#002b36"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[colors.dim]
black = "#001317"
red = "#aa1b1b"
green = "#5f7100"
yellow = "#8d6700"
blue = "#1d69a8"
magenta = "#a62768"
cyan = "#1f7972"
white = "#bbb5a5"
