"$schema" = "https://yazi-rs.github.io/schemas/flavor.json"

# Catppuccin Frappé Theme - French vanilla
# Official colors from: https://github.com/catppuccin/palette
# Based on warm dark theme with French blue undertones

[manager]
cwd = { fg = "#babbf1" }                                # lavender - current directory name
hovered = { bg = "#51576d", fg = "#c6d0f5" }            # surface1 bg, text fg - hovered file
preview_hovered = { bg = "#414559", fg = "#c6d0f5" }    # surface0 bg, text fg - preview area hovered
find = { bg = "#ef9f76", fg = "#303446", bold = true }  # peach bg, base fg - search highlight
found = { bg = "#a6d189", fg = "#303446", bold = true } # green bg, base fg - search results

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#626880", bg = "#626880" } # surface2 border

[tabs]
inactive = { fg = "#a5adce", bg = "#303446" }            # subtext0 fg, base bg - inactive tabs
active = { fg = "#babbf1", bg = "#414559", bold = true } # lavender fg, surface0 bg - active tab

[border]
symbol = "│"
style = { fg = "#626880" } # surface2 - subtle borders

[completion]
border = { fg = "#626880" }                              # surface2
active = { bg = "#414559", fg = "#c6d0f5", bold = true } # surface0 bg, text fg
inactive = { bg = "#303446", fg = "#a5adce" }            # base bg, subtext0 fg

[mode]
normal = { bg = "#8caaee", fg = "#303446", bold = true } # blue bg, base fg
select = { bg = "#a6d189", fg = "#303446", bold = true } # green bg, base fg
unset = { bg = "#ef9f76", fg = "#303446", bold = true }  # peach bg, base fg

[which]
cols = 3
mask = { bg = "#292c3c" }            # mantle - overlay background
cand = { fg = "#8caaee" }            # blue - command candidates
rest = { fg = "#737994" }            # overlay0 - remaining text
desc = { fg = "#ef9f76" }            # peach - descriptions
separator = "  "
separator_style = { fg = "#626880" } # surface2

[confirm]
border = { fg = "#e78284" }             # red border for attention
title = { fg = "#e78284", bold = true } # red title
content = { fg = "#c6d0f5" }            # text content

[spot]
title = { fg = "#babbf1", bold = true }                  # lavender title
origin = { fg = "#f2d5cf" }                              # rosewater - file origin
line = { fg = "#e5c890" }                                # yellow - line numbers
keyword = { fg = "#ca9ee6", bold = true, italic = true } # mauve keywords

[input]
border = { fg = "#8caaee" }                                # blue
title = { fg = "#8caaee", bold = true }                    # blue
value = { fg = "#c6d0f5" }                                 # text
selected = { bg = "#737994", fg = "#c6d0f5", bold = true } # overlay0 bg, text fg

[pick]
border = { fg = "#a6d189" }              # green
active = { fg = "#ef9f76", bold = true } # peach
inactive = { fg = "#737994" }            # overlay0

[notify]
title = { fg = "#babbf1", bold = true } # lavender
content = { fg = "#c6d0f5" }            # text
error = { fg = "#e78284", bold = true } # red
warn = { fg = "#e5c890", bold = true }  # yellow
info = { fg = "#8caaee" }               # blue

[help]
on = { fg = "#ef9f76", bold = true }                      # peach
run = { fg = "#ca9ee6", italic = true }                   # mauve
desc = { fg = "#c6d0f5" }                                 # text
hovered = { bg = "#414559", fg = "#ef9f76", bold = true } # surface0 bg, peach fg
footer = { fg = "#a5adce", bg = "#303446" }               # subtext0 fg, base bg

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#ca9ee6" }, # mauve

    # Videos
    { mime = "video/*", fg = "#e5c890" }, # yellow

    # Audio
    { mime = "audio/*", fg = "#a6d189" }, # green

    # Archives
    { mime = "application/zip", fg = "#e78284" },             # red
    { mime = "application/gzip", fg = "#e78284" },            # red
    { mime = "application/x-tar", fg = "#e78284" },           # red
    { mime = "application/x-bzip2", fg = "#e78284" },         # red
    { mime = "application/x-7z-compressed", fg = "#e78284" }, # red

    # Documents
    { mime = "application/pdf", fg = "#e78284" }, # red
    { mime = "text/plain", fg = "#c6d0f5" },      # text
    { name = "*.md", fg = "#8caaee" },            # blue - markdown
    { name = "*.rst", fg = "#8caaee" },           # blue - reStructuredText

    # Configuration files
    { name = "*.toml", fg = "#ef9f76" }, # peach
    { name = "*.yaml", fg = "#ef9f76" }, # peach  
    { name = "*.yml", fg = "#ef9f76" },  # peach
    { name = "*.json", fg = "#ef9f76" }, # peach
    { name = "*.xml", fg = "#ef9f76" },  # peach

    # Code files
    { name = "*.js", fg = "#e5c890" },  # yellow
    { name = "*.ts", fg = "#8caaee" },  # blue
    { name = "*.jsx", fg = "#99d1db" }, # sky
    { name = "*.tsx", fg = "#99d1db" }, # sky
    { name = "*.py", fg = "#e5c890" },  # yellow
    { name = "*.rs", fg = "#ef9f76" },  # peach
    { name = "*.go", fg = "#99d1db" },  # sky
    { name = "*.c", fg = "#8caaee" },   # blue
    { name = "*.cpp", fg = "#8caaee" }, # blue
    { name = "*.h", fg = "#ca9ee6" },   # mauve

    # Shell scripts
    { name = "*.sh", fg = "#a6d189" },   # green
    { name = "*.bash", fg = "#a6d189" }, # green
    { name = "*.zsh", fg = "#a6d189" },  # green
    { name = "*.fish", fg = "#a6d189" }, # green

    # Special files
    { name = "README*", fg = "#8caaee", bold = true }, # blue
    { name = "LICENSE*", fg = "#e5c890" },             # yellow
    { name = "Makefile", fg = "#a6d189" },             # green
    { name = "Dockerfile", fg = "#8caaee" },           # blue
    { name = ".gitignore", fg = "#737994" },           # overlay0
    { name = ".env*", fg = "#e5c890" },                # yellow
]

[icon]
prepend_rules = [
    # Directories
    { name = "*/", text = "", fg = "#8caaee" },         # blue
    { name = ".config/", text = "", fg = "#ef9f76" },   # peach
    { name = ".git/", text = "", fg = "#e78284" },      # red
    { name = "Desktop/", text = "", fg = "#babbf1" },   # lavender
    { name = "Documents/", text = "", fg = "#8caaee" }, # blue
    { name = "Downloads/", text = "", fg = "#a6d189" }, # green
    { name = "Pictures/", text = "", fg = "#ca9ee6" },  # mauve
    { name = "Music/", text = "", fg = "#a6d189" },     # green
    { name = "Videos/", text = "", fg = "#e5c890" },    # yellow

    # Files
    { name = "*.rs", text = "", fg = "#ef9f76" },   # peach
    { name = "*.js", text = "", fg = "#e5c890" },   # yellow
    { name = "*.ts", text = "", fg = "#8caaee" },   # blue
    { name = "*.py", text = "", fg = "#e5c890" },   # yellow
    { name = "*.json", text = "", fg = "#ef9f76" }, # peach
    { name = "*.toml", text = "", fg = "#ef9f76" }, # peach
    { name = "*.md", text = "", fg = "#8caaee" },   # blue
    { name = "*.txt", text = "", fg = "#c6d0f5" },  # text
    { name = "*.pdf", text = "", fg = "#e78284" },  # red
    { name = "*.zip", text = "", fg = "#e78284" },  # red
    { name = "*.png", text = "", fg = "#ca9ee6" },  # mauve
    { name = "*.jpg", text = "", fg = "#ca9ee6" },  # mauve
    { name = "*.gif", text = "", fg = "#ca9ee6" },  # mauve
    { name = "*.mp4", text = "", fg = "#e5c890" },  # yellow
    { name = "*.mp3", text = "", fg = "#a6d189" },  # green
    { name = "*.wav", text = "", fg = "#a6d189" },  # green
]

rules = [
    # Default fallbacks
    { mime = "inode/directory", text = "", fg = "#8caaee" },  # blue
    { mime = "text/*", text = "", fg = "#c6d0f5" },           # text
    { mime = "application/json", text = "", fg = "#ef9f76" }, # peach
    { mime = "*/javascript", text = "", fg = "#e5c890" },     # yellow
    { is = "link", text = "", fg = "#99d1db" },               # sky
    { is = "orphan", text = "", fg = "#e78284" },             # red
    { name = "*", text = "", fg = "#c6d0f5" },                # text - default
]

[tasks]
border = { fg = "#8caaee" }                               # blue
title = { fg = "#8caaee", bold = true }                   # blue
hovered = { bg = "#414559", fg = "#c6d0f5", bold = true } # surface0 bg, text fg

[cmp]
border = { fg = "#8caaee" }                 # blue
active = { bg = "#414559", fg = "#c6d0f5" } # surface0 bg, text fg  
inactive = { fg = "#a5adce" }               # subtext0

# Progress bars and loading states use peach accent
[progress]
label = { fg = "#c6d0f5", bold = true }   # text
percent = { fg = "#ef9f76", bold = true } # peach
border = { fg = "#626880" }               # surface2

# Loading animation accent
[loading]
indicator = { fg = "#ef9f76", bold = true } # peach
