# Rosé Pine Moon theme for Rio Terminal
# Based on the official Rosé Pine Moon color palette: https://rosepinetheme.com/

[colors]
# Background colors
background = '#232136' # Base - Primary background
foreground = '#e0def4' # Text - High contrast foreground

# Normal colors
black = '#393552'   # Overlay
red = '#eb6f92'     # Love - Per favore ama tutti
green = '#3e8fb0'   # Pine - Fresh winter greenery
yellow = '#f6c177'  # Gold - Lemon tea on a summer morning
blue = '#9ccfd8'    # Foam - Saltwater tidepools
magenta = '#c4a7e7' # Iris - Smells of groundedness
cyan = '#ea9a97'    # Rose - A beautiful yet cautious blossom
white = '#e0def4'   # Text

# Bright colors
light-black = '#6e6a86'   # Muted - Low contrast foreground
light-red = '#eb6f92'     # Love
light-green = '#3e8fb0'   # Pine
light-yellow = '#f6c177'  # Gold
light-blue = '#9ccfd8'    # Foam
light-magenta = '#c4a7e7' # Iris
light-cyan = '#ea9a97'    # Rose
light-white = '#e0def4'   # Text

# Dim colors
dim-black = '#2a283e'   # Highlight Low
dim-red = '#eb6f92'     # Love
dim-green = '#3e8fb0'   # Pine
dim-yellow = '#f6c177'  # Gold
dim-blue = '#9ccfd8'    # Foam
dim-magenta = '#c4a7e7' # Iris
dim-cyan = '#ea9a97'    # Rose
dim-white = '#908caa'   # Subtle

# UI colors
cursor = '#56526e'    # Highlight High
vi-cursor = '#56526e' # Highlight High

# Selection
selection-foreground = '#e0def4' # Text
selection-background = '#44415a' # Highlight Med

# Search
search-match-background = '#44415a'         # Highlight Med
search-match-foreground = '#e0def4'         # Text
search-focused-match-background = '#56526e' # Highlight High
search-focused-match-foreground = '#e0def4' # Text

# Navigation/Tabs
tabs = '#2a273f'                   # Surface
tabs-foreground = '#908caa'        # Subtle
tabs-active = '#393552'            # Overlay
tabs-active-foreground = '#e0def4' # Text
tabs-active-highlight = '#c4a7e7'  # Iris
bar = '#232136'                    # Base
