# Sherlock Configuration - macOS Tahoe Style
# Modern, clean application launcher inspired by macOS design

[appearance]
width = 800
height = 600
gsk_renderer = "cairo"  # Best performance for blur effects
icon_size = 24
use_base_css = true
opacity = 0.95          # Slight transparency for vibrancy effect

[behavior]
animate = true
use_xdg_data_dir_icons = false

[binds]
modifier = "super"      # CMD key like macOS
exec_inplace = "super+return"
context = "super+i"

[backdrop]
enable = true
opacity = 0.8
edge = "top"

[expand]
enable = true
edge = "top"
margin = 40

[caching]
enable = true

[status_bar]
enable = false          # Clean interface like macOS Spotlight

[runtime]
center = true
daemonize = false

[default_apps]
terminal = "ghostty"
browser = "firefox"

[units]
lengths = "meter"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "eur"

[debug]
try_suppress_errors = false
try_suppress_warnings = true
