# One Dark Pro Theme for Yazi
# A sleek dark theme inspired by Atom One Dark and VS Code One Dark Pro
# Based on the popular One Dark color scheme

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# One Dark Pro Color Palette
# Background colors:
# - bg: #282c34 (main background)
# - bg_alt: #21252b (darker background)
# - bg_highlight: #2c323c (highlight background)
# - bg_popup: #3e4452 (popup background)
# - border: #181a1f (border color)
# - text: #abb2bf (primary text)
# - text_alt: #5c6370 (secondary text)
# - text_dark: #3e4452 (dark text)
# - red: #e06c75 (red)
# - green: #98c379 (green)
# - yellow: #e5c07b (yellow)
# - blue: #61afef (blue)
# - purple: #c678dd (purple)
# - cyan: #56b6c2 (cyan)
# - orange: #d19a66 (orange)
# - pink: #ff6ac1 (pink)

# : Manager {{{

[mgr]
cwd = { fg = "#61afef", bold = true } # blue - current directory

# Hovered states
hovered = { bg = "#2c323c", bold = true }              # bg_highlight
preview_hovered = { underline = true, fg = "#abb2bf" } # text

# Find/search
find_keyword = { fg = "#e5c07b", bold = true, italic = true, underline = true } # yellow
find_position = { fg = "#c678dd", bg = "#282c34", bold = true, italic = true }  # purple on bg

# Symlink
symlink_target = { fg = "#61afef", italic = true } # blue

# Markers
marker_copied = { fg = "#282c34", bg = "#56b6c2" }   # bg on cyan
marker_cut = { fg = "#282c34", bg = "#e06c75" }      # bg on red
marker_marked = { fg = "#282c34", bg = "#c678dd" }   # bg on purple
marker_selected = { fg = "#282c34", bg = "#e5c07b" } # bg on yellow

# Counts
count_copied = { fg = "#abb2bf", bg = "#56b6c2" }   # text on cyan
count_cut = { fg = "#abb2bf", bg = "#e06c75" }      # text on red
count_selected = { fg = "#abb2bf", bg = "#e5c07b" } # text on yellow

# Border
border_symbol = "│"
border_style = { fg = "#181a1f" } # border

# Syntax highlighting
syntect_theme = "tmtheme.xml"

# : }}}

# : Tabs {{{

[tabs]
active = { fg = "#abb2bf", bg = "#61afef", bold = true } # text on blue
inactive = { fg = "#5c6370", bg = "#21252b" }            # text_alt on bg_alt

# Tab separators
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}

# : Mode indicator {{{

[mode]
normal_main = { fg = "#abb2bf", bg = "#61afef", bold = true } # text on blue
normal_alt = { fg = "#61afef", bg = "#21252b" }               # blue on bg_alt

select_main = { fg = "#abb2bf", bg = "#e06c75", bold = true } # text on red  
select_alt = { fg = "#e06c75", bg = "#21252b" }               # red on bg_alt

unset_main = { fg = "#abb2bf", bg = "#e5c07b", bold = true } # text on yellow
unset_alt = { fg = "#e5c07b", bg = "#21252b" }               # yellow on bg_alt

# : }}}

# : Status bar {{{

[status]
overall = { fg = "#abb2bf", bg = "#282c34" } # text on bg
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# File permissions
perm_sep = { fg = "#181a1f" }   # border
perm_type = { fg = "#61afef" }  # blue - file type
perm_read = { fg = "#e5c07b" }  # yellow - read permission
perm_write = { fg = "#e06c75" } # red - write permission  
perm_exec = { fg = "#98c379" }  # green - execute permission

# Progress indicators
progress_label = { fg = "#abb2bf", bold = true }     # text
progress_normal = { fg = "#61afef", bg = "#21252b" } # blue on bg_alt
progress_error = { fg = "#e06c75", bg = "#21252b" }  # red on bg_alt

# : }}}

# : Which-key menu {{{

[which]
cols = 3
mask = { bg = "#282c34" }              # bg background
cand = { fg = "#56b6c2", bold = true } # cyan - candidates
rest = { fg = "#5c6370" }              # text_alt - rest of command
desc = { fg = "#c678dd" }              # purple - descriptions
separator = "  "
separator_style = { fg = "#181a1f" }   # border

# : }}}

# : Confirmation dialog {{{

[confirm]
border = { fg = "#61afef" }             # blue
title = { fg = "#61afef", bold = true } # blue

# : }}}

# : File search/spotter {{{

[spot]
border = { fg = "#61afef" }             # blue
title = { fg = "#61afef", bold = true } # blue

# Table view
tbl_col = { fg = "#56b6c2", bold = true }     # cyan - column headers
tbl_cell = { fg = "#e5c07b", bg = "#21252b" } # yellow on bg_alt

# : }}}

# : Notifications {{{

[notify]
title_info = { fg = "#61afef", bold = true }  # blue
title_warn = { fg = "#e5c07b", bold = true }  # yellow  
title_error = { fg = "#e06c75", bold = true } # red

# Notification icons
icon_info = ""  # info icon
icon_warn = ""  # warning icon
icon_error = "" # error icon

# : }}}

# : File picker {{{

[pick]
border = { fg = "#61afef" }              # blue
active = { fg = "#c678dd", bold = true } # purple - active item
inactive = { fg = "#5c6370" }            # text_alt - inactive items

# : }}}

# : Input field {{{

[input]
border = { fg = "#61afef" }                   # blue
title = { fg = "#56b6c2", bold = true }       # cyan
value = { fg = "#abb2bf" }                    # text
selected = { fg = "#282c34", bg = "#c678dd" } # bg on purple

# : }}}

# : Command completion {{{

[cmp]
border = { fg = "#61afef" }                 # blue
active = { fg = "#282c34", bg = "#56b6c2" } # bg on cyan
inactive = { fg = "#5c6370" }               # text_alt

# Completion icons
icon_file = ""    # file icon
icon_folder = ""  # folder icon  
icon_command = "" # command icon

# : }}}

# : Task manager {{{

[tasks]
border = { fg = "#61afef" }                    # blue
title = { fg = "#56b6c2", bold = true }        # cyan
hovered = { fg = "#c678dd", underline = true } # purple

# : }}}

# : Help menu {{{

[help]
on = { fg = "#56b6c2", bold = true }                      # cyan - enabled features
run = { fg = "#c678dd", bold = true }                     # purple - runnable commands
desc = { fg = "#5c6370" }                                 # text_alt - descriptions
hovered = { fg = "#282c34", bg = "#ff6ac1", bold = true } # bg on pink
footer = { fg = "#282c34", bg = "#abb2bf" }               # bg on text

# : }}}

# : File type colors {{{

[filetype]
rules = [
    # Images - pink color for visual files
    { mime = "image/*", fg = "#ff6ac1" },

    # Audio/Video - red color for media
    { mime = "audio/*", fg = "#e06c75" },
    { mime = "video/*", fg = "#e06c75" },

    # Archives - orange color for compressed files
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d19a66" },

    # Documents - blue color for text documents
    { mime = "application/{pdf,doc,rtf,odt,ods,odp}", fg = "#61afef" },
    { mime = "text/*", fg = "#61afef" },

    # Code files - cyan color for source code
    { mime = "application/{javascript,typescript,json,xml}", fg = "#56b6c2" },

    # Special file states
    { name = "*", is = "orphan", bg = "#e06c75", fg = "#abb2bf" }, # red background
    { name = "*", is = "exec", fg = "#e5c07b", bold = true },      # yellow for executables

    # Dummy/placeholder files
    { name = "*", is = "dummy", bg = "#5c6370", fg = "#abb2bf" },

    # Directories - purple color
    { name = "*/", fg = "#c678dd", bold = true },

    # Default fallback
    { name = "*", fg = "#abb2bf" }, # text color
]

# : }}}

# : Icons {{{

[icon]
globs = []

# Directory icons
dirs = [
    { name = ".git", text = "", fg = "#e06c75" },         # red
    { name = ".github", text = "", fg = "#e06c75" },      # red
    { name = ".config", text = "", fg = "#61afef" },      # blue
    { name = ".npm", text = "", fg = "#e06c75" },         # red
    { name = ".vscode", text = "", fg = "#61afef" },      # blue
    { name = "node_modules", text = "", fg = "#d19a66" }, # orange
    { name = "Desktop", text = "", fg = "#56b6c2" },      # cyan
    { name = "Documents", text = "", fg = "#61afef" },    # blue
    { name = "Downloads", text = "", fg = "#d19a66" },    # orange
    { name = "Pictures", text = "", fg = "#ff6ac1" },     # pink
    { name = "Music", text = "", fg = "#e06c75" },        # red
    { name = "Videos", text = "", fg = "#e06c75" },       # red
    { name = "Development", text = "", fg = "#56b6c2" },  # cyan
    { name = "Projects", text = "", fg = "#56b6c2" },     # cyan
]

# File icons
files = [
    # Git files
    { name = ".gitignore", text = "", fg = "#e06c75" },
    { name = ".gitconfig", text = "", fg = "#e06c75" },

    # Config files
    { name = ".bashrc", text = "", fg = "#61afef" },
    { name = ".zshrc", text = "", fg = "#61afef" },
    { name = ".vimrc", text = "", fg = "#61afef" },

    # Web development
    { name = "*.html", text = "", fg = "#e06c75" }, # red
    { name = "*.css", text = "", fg = "#61afef" },  # blue
    { name = "*.scss", text = "", fg = "#ff6ac1" }, # pink
    { name = "*.js", text = "", fg = "#e5c07b" },   # yellow
    { name = "*.ts", text = "", fg = "#61afef" },   # blue
    { name = "*.jsx", text = "", fg = "#56b6c2" },  # cyan
    { name = "*.tsx", text = "", fg = "#56b6c2" },  # cyan

    # Programming languages
    { name = "*.py", text = "", fg = "#e5c07b" },   # yellow
    { name = "*.rs", text = "", fg = "#e06c75" },   # red
    { name = "*.go", text = "", fg = "#56b6c2" },   # cyan
    { name = "*.cpp", text = "", fg = "#61afef" },  # blue
    { name = "*.c", text = "", fg = "#61afef" },    # blue
    { name = "*.java", text = "", fg = "#d19a66" }, # orange

    # Data files
    { name = "*.json", text = "", fg = "#e5c07b" }, # yellow
    { name = "*.yaml", text = "", fg = "#c678dd" }, # purple
    { name = "*.yml", text = "", fg = "#c678dd" },  # purple
    { name = "*.toml", text = "", fg = "#c678dd" }, # purple

    # Documents
    { name = "*.pdf", text = "", fg = "#e06c75" }, # red
    { name = "*.md", text = "", fg = "#56b6c2" },  # cyan
    { name = "*.txt", text = "", fg = "#abb2bf" }, # text

    # Images
    { name = "*.png", text = "", fg = "#ff6ac1" }, # pink
    { name = "*.jpg", text = "", fg = "#ff6ac1" }, # pink
    { name = "*.svg", text = "", fg = "#e5c07b" }, # yellow

    # Media files
    { name = "*.mp3", text = "", fg = "#e06c75" }, # red
    { name = "*.mp4", text = "", fg = "#e06c75" }, # red

    # Archives
    { name = "*.zip", text = "", fg = "#d19a66" }, # orange
    { name = "*.tar", text = "", fg = "#d19a66" }, # orange

    # Special files
    { name = "Dockerfile", text = "", fg = "#61afef" }, # blue
    { name = "Makefile", text = "", fg = "#56b6c2" },   # cyan
    { name = "README.md", text = "", fg = "#e5c07b" },  # yellow
]

# Extensions fallback
exts = [
    { name = "py", text = "", fg = "#e5c07b" },   # yellow
    { name = "js", text = "", fg = "#e5c07b" },   # yellow
    { name = "ts", text = "", fg = "#61afef" },   # blue
    { name = "rs", text = "", fg = "#e06c75" },   # red
    { name = "html", text = "", fg = "#e06c75" }, # red
    { name = "css", text = "", fg = "#61afef" },  # blue
    { name = "png", text = "", fg = "#ff6ac1" },  # pink
    { name = "jpg", text = "", fg = "#ff6ac1" },  # pink
    { name = "*", text = "", fg = "#abb2bf" },    # text
]

# : }}}
