# Rose Pine Theme for Yazi
# A warm, elegant dark theme inspired by the Rose Pine color palette
# https://rosepinetheme.com/

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# Rose Pine Color Palette
# Background colors:
# - base: #191724 (main background)
# - surface: #1f1d2e (surface background)
# - overlay: #26233a (overlay background)
# - muted: #6e6a86 (muted text)
# - subtle: #908caa (subtle text)
# - text: #e0def4 (main text)
# - love: #eb6f92 (red/pink)
# - gold: #f6c177 (yellow/orange)
# - rose: #ebbcba (light pink)
# - pine: #31748f (blue/teal)
# - foam: #9ccfd8 (light blue/cyan)
# - iris: #c4a7e7 (purple)
# - highlight_low: #21202e (dark highlight)
# - highlight_med: #403d52 (medium highlight)
# - highlight_high: #524f67 (light highlight)

# : Manager {{{

[mgr]
cwd = { fg = "#9ccfd8", bold = true }  # foam - current directory

# Hovered states
hovered = { bg = "#403d52", bold = true }  # highlight_med
preview_hovered = { underline = true, fg = "#e0def4" }  # text

# Find/search
find_keyword = { fg = "#f6c177", bold = true, italic = true, underline = true }  # gold
find_position = { fg = "#c4a7e7", bg = "#191724", bold = true, italic = true }  # iris on base

# Symlink
symlink_target = { fg = "#9ccfd8", italic = true }  # foam

# Markers
marker_copied = { fg = "#191724", bg = "#31748f" }  # base on pine
marker_cut = { fg = "#191724", bg = "#eb6f92" }     # base on love
marker_marked = { fg = "#191724", bg = "#c4a7e7" }  # base on iris
marker_selected = { fg = "#191724", bg = "#f6c177" } # base on gold

# Counts
count_copied = { fg = "#e0def4", bg = "#31748f" }   # text on pine
count_cut = { fg = "#e0def4", bg = "#eb6f92" }      # text on love
count_selected = { fg = "#e0def4", bg = "#f6c177" } # text on gold

# Border
border_symbol = "│"
border_style = { fg = "#6e6a86" }  # muted

# Syntax highlighting
syntect_theme = ""

# : }}}

# : Tabs {{{

[tabs]
active = { fg = "#e0def4", bg = "#31748f", bold = true }     # text on pine
inactive = { fg = "#908caa", bg = "#26233a" }                # subtle on overlay

# Tab separators (Powerline style)
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}

# : Mode indicator {{{

[mode]
normal_main = { fg = "#e0def4", bg = "#31748f", bold = true }  # text on pine
normal_alt = { fg = "#31748f", bg = "#26233a" }               # pine on overlay

select_main = { fg = "#e0def4", bg = "#eb6f92", bold = true }  # text on love  
select_alt = { fg = "#eb6f92", bg = "#26233a" }                # love on overlay

unset_main = { fg = "#e0def4", bg = "#f6c177", bold = true }   # text on gold
unset_alt = { fg = "#f6c177", bg = "#26233a" }                 # gold on overlay

# : }}}

# : Status bar {{{

[status]
overall = { fg = "#e0def4", bg = "#191724" }  # text on base
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# File permissions
perm_sep = { fg = "#6e6a86" }      # muted
perm_type = { fg = "#31748f" }     # pine - file type
perm_read = { fg = "#f6c177" }     # gold - read permission
perm_write = { fg = "#eb6f92" }    # love - write permission  
perm_exec = { fg = "#9ccfd8" }     # foam - execute permission

# Progress indicators
progress_label = { fg = "#e0def4", bold = true }           # text
progress_normal = { fg = "#31748f", bg = "#26233a" }      # pine on overlay
progress_error = { fg = "#eb6f92", bg = "#26233a" }       # love on overlay

# : }}}

# : Which-key menu {{{

[which]
cols = 3
mask = { bg = "#191724" }                # base background
cand = { fg = "#9ccfd8", bold = true }   # foam - candidates
rest = { fg = "#6e6a86" }               # muted - rest of command
desc = { fg = "#c4a7e7" }               # iris - descriptions
separator = "  "
separator_style = { fg = "#6e6a86" }    # muted

# : }}}

# : Confirmation dialog {{{

[confirm]
border = { fg = "#31748f" }                        # pine
title = { fg = "#31748f", bold = true }            # pine

# : }}}

# : File search/spotter {{{

[spot]
border = { fg = "#31748f" }              # pine
title = { fg = "#31748f", bold = true }  # pine

# Table view
tbl_col = { fg = "#9ccfd8", bold = true }      # foam - column headers
tbl_cell = { fg = "#f6c177", bg = "#26233a" }  # gold on overlay

# : }}}

# : Notifications {{{

[notify]
title_info = { fg = "#31748f", bold = true }   # pine
title_warn = { fg = "#f6c177", bold = true }   # gold  
title_error = { fg = "#eb6f92", bold = true }  # love

# Notification icons
icon_info = ""   # info icon
icon_warn = ""   # warning icon
icon_error = ""  # error icon

# : }}}

# : File picker {{{

[pick]
border = { fg = "#31748f" }                    # pine
active = { fg = "#c4a7e7", bold = true }       # iris - active item
inactive = { fg = "#908caa" }                  # subtle - inactive items

# : }}}

# : Input field {{{

[input]
border = { fg = "#31748f" }             # pine
title = { fg = "#9ccfd8", bold = true } # foam
value = { fg = "#e0def4" }              # text
selected = { fg = "#191724", bg = "#c4a7e7" }  # base on iris

# : }}}

# : Command completion {{{

[cmp]
border = { fg = "#31748f" }                    # pine
active = { fg = "#191724", bg = "#9ccfd8" }    # base on foam
inactive = { fg = "#908caa" }                  # subtle

# Completion icons
icon_file = ""     # file icon
icon_folder = ""   # folder icon  
icon_command = ""  # command icon

# : }}}

# : Task manager {{{

[tasks]
border = { fg = "#31748f" }                      # pine
title = { fg = "#9ccfd8", bold = true }          # foam
hovered = { fg = "#c4a7e7", underline = true }   # iris

# : }}}

# : Help menu {{{

[help]
on = { fg = "#9ccfd8", bold = true }    # foam - enabled features
run = { fg = "#c4a7e7", bold = true }   # iris - runnable commands
desc = { fg = "#908caa" }               # subtle - descriptions
hovered = { fg = "#191724", bg = "#ebbcba", bold = true }  # base on rose
footer = { fg = "#191724", bg = "#e0def4" }                # base on text

# : }}}

# : File type colors {{{

[filetype]
rules = [
    # Images - rose color for visual files
    { mime = "image/*", fg = "#ebbcba" },

    # Audio/Video - love color for media
    { mime = "audio/*", fg = "#eb6f92" },
    { mime = "video/*", fg = "#eb6f92" },

    # Archives - gold color for compressed files
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f6c177" },

    # Documents - pine color for text documents
    { mime = "application/{pdf,doc,rtf,odt,ods,odp}", fg = "#31748f" },
    { mime = "text/*", fg = "#31748f" },

    # Code files - foam color for source code
    { mime = "application/{javascript,typescript,json,xml}", fg = "#9ccfd8" },

    # Special file states
    { name = "*", is = "orphan", bg = "#eb6f92", fg = "#e0def4" },    # love background
    { name = "*", is = "exec", fg = "#f6c177", bold = true },         # gold for executables

    # Dummy/placeholder files
    { name = "*", is = "dummy", bg = "#6e6a86", fg = "#e0def4" },

    # Directories - iris color
    { name = "*/", fg = "#c4a7e7", bold = true },

    # Default fallback
    { name = "*", fg = "#e0def4" },  # text color
]

# : }}}

# : Icons {{{

[icon]
# Global icon styling
globs = []

# Directory icons with Rose Pine theming
dirs = [
    { name = ".git", text = "", fg = "#eb6f92" },           # love
    { name = ".github", text = "", fg = "#eb6f92" },        # love
    { name = ".config", text = "", fg = "#31748f" },        # pine
    { name = ".npm", text = "", fg = "#eb6f92" },           # love
    { name = ".vscode", text = "", fg = "#31748f" },        # pine
    { name = "node_modules", text = "", fg = "#f6c177" },   # gold
    { name = "Desktop", text = "", fg = "#9ccfd8" },        # foam
    { name = "Documents", text = "", fg = "#31748f" },      # pine
    { name = "Downloads", text = "", fg = "#f6c177" },      # gold
    { name = "Pictures", text = "", fg = "#ebbcba" },       # rose
    { name = "Music", text = "", fg = "#eb6f92" },          # love
    { name = "Videos", text = "", fg = "#eb6f92" },         # love
    { name = "Development", text = "", fg = "#9ccfd8" },    # foam
    { name = "Projects", text = "", fg = "#9ccfd8" },       # foam
]

# File icons with Rose Pine colors
files = [
    # Git and version control
    { name = ".gitignore", text = "", fg = "#eb6f92" },
    { name = ".gitconfig", text = "", fg = "#eb6f92" },
    { name = ".gitattributes", text = "", fg = "#eb6f92" },

    # Config files
    { name = ".bashrc", text = "", fg = "#31748f" },
    { name = ".zshrc", text = "", fg = "#31748f" },
    { name = ".vimrc", text = "", fg = "#31748f" },
    { name = ".tmux.conf", text = "", fg = "#31748f" },

    # Web development
    { name = "*.html", text = "", fg = "#eb6f92" },         # love
    { name = "*.css", text = "", fg = "#31748f" },          # pine
    { name = "*.scss", text = "", fg = "#ebbcba" },         # rose
    { name = "*.js", text = "", fg = "#f6c177" },           # gold
    { name = "*.ts", text = "", fg = "#31748f" },           # pine
    { name = "*.jsx", text = "", fg = "#9ccfd8" },          # foam
    { name = "*.tsx", text = "", fg = "#9ccfd8" },          # foam
    { name = "*.vue", text = "", fg = "#31748f" },          # pine
    { name = "*.svelte", text = "", fg = "#eb6f92" },       # love

    # Programming languages
    { name = "*.py", text = "", fg = "#f6c177" },           # gold
    { name = "*.rs", text = "", fg = "#eb6f92" },           # love
    { name = "*.go", text = "", fg = "#9ccfd8" },           # foam
    { name = "*.cpp", text = "", fg = "#31748f" },          # pine
    { name = "*.c", text = "", fg = "#31748f" },            # pine
    { name = "*.java", text = "", fg = "#eb6f92" },         # love
    { name = "*.php", text = "", fg = "#c4a7e7" },          # iris

    # Data files
    { name = "*.json", text = "", fg = "#f6c177" },         # gold
    { name = "*.xml", text = "", fg = "#f6c177" },          # gold
    { name = "*.yaml", text = "", fg = "#c4a7e7" },         # iris
    { name = "*.yml", text = "", fg = "#c4a7e7" },          # iris
    { name = "*.toml", text = "", fg = "#c4a7e7" },         # iris

    # Documents
    { name = "*.pdf", text = "", fg = "#eb6f92" },          # love
    { name = "*.doc", text = "", fg = "#31748f" },          # pine
    { name = "*.docx", text = "", fg = "#31748f" },         # pine
    { name = "*.md", text = "", fg = "#9ccfd8" },           # foam
    { name = "*.txt", text = "", fg = "#e0def4" },          # text

    # Images
    { name = "*.png", text = "", fg = "#ebbcba" },          # rose
    { name = "*.jpg", text = "", fg = "#ebbcba" },          # rose
    { name = "*.jpeg", text = "", fg = "#ebbcba" },         # rose
    { name = "*.gif", text = "", fg = "#ebbcba" },          # rose
    { name = "*.svg", text = "", fg = "#f6c177" },          # gold
    { name = "*.ico", text = "", fg = "#f6c177" },          # gold

    # Media files
    { name = "*.mp3", text = "", fg = "#eb6f92" },          # love
    { name = "*.wav", text = "", fg = "#eb6f92" },          # love
    { name = "*.flac", text = "", fg = "#eb6f92" },         # love
    { name = "*.mp4", text = "", fg = "#eb6f92" },          # love
    { name = "*.mkv", text = "", fg = "#eb6f92" },          # love
    { name = "*.avi", text = "", fg = "#eb6f92" },          # love

    # Archives
    { name = "*.zip", text = "", fg = "#f6c177" },          # gold
    { name = "*.tar", text = "", fg = "#f6c177" },          # gold
    { name = "*.gz", text = "", fg = "#f6c177" },           # gold
    { name = "*.rar", text = "", fg = "#f6c177" },          # gold
    { name = "*.7z", text = "", fg = "#f6c177" },           # gold

    # Special files
    { name = "Dockerfile", text = "", fg = "#31748f" },     # pine
    { name = "docker-compose.yml", text = "", fg = "#31748f" }, # pine
    { name = "Makefile", text = "", fg = "#9ccfd8" },       # foam
    { name = "README.md", text = "", fg = "#f6c177" },      # gold
    { name = "LICENSE", text = "", fg = "#c4a7e7" },        # iris
]

# Extensions-based icons (fallback)
exts = [
    # Programming
    { name = "py", text = "", fg = "#f6c177" },             # gold
    { name = "js", text = "", fg = "#f6c177" },             # gold
    { name = "ts", text = "", fg = "#31748f" },             # pine
    { name = "rs", text = "", fg = "#eb6f92" },             # love
    { name = "go", text = "", fg = "#9ccfd8" },             # foam
    { name = "cpp", text = "", fg = "#31748f" },            # pine
    { name = "c", text = "", fg = "#31748f" },              # pine

    # Web
    { name = "html", text = "", fg = "#eb6f92" },           # love
    { name = "css", text = "", fg = "#31748f" },            # pine
    { name = "scss", text = "", fg = "#ebbcba" },           # rose

    # Images
    { name = "png", text = "", fg = "#ebbcba" },            # rose
    { name = "jpg", text = "", fg = "#ebbcba" },            # rose
    { name = "svg", text = "", fg = "#f6c177" },            # gold

    # Default file icon
    { name = "*", text = "", fg = "#e0def4" },              # text
]

# : }}}
