# ================================
# Yazi 现代化配置文件 (yazi.toml)
# 基于人体工程学和现代设计原则
# ================================

[magr]
# 排序方式 - 智能混合排序
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

# 显示设置 - 提升可读性
show_hidden = false
show_symlink = true
linemode = "size_and_mtime" # 显示大小和修改时间

# 滚动设置 - 减少眼疲劳
scrolloff = 5 # 保持上下5行缓冲区，更好的视觉效果

# 鼠标支持 - 现代交互体验
mouse_events = ["click", "scroll"]

[preview]
# 预览设置 - 智能预览提升工作效率
tab_size = 2
max_width = 600
max_height = 900

# 图像预览优化
image_filter = "triangle"
image_quality = 75

# 缓存设置 - 提升性能
cache_dir = ""

[opener]
# 文件打开器 - 针对不同文件类型的最优化配置

# 文本文件 - 使用现代编辑器
edit = [
    { run = 'nvim "$1"', desc = "编辑文件", block = true, for = "unix" },
    { run = 'code "$1"', desc = "VS Code 编辑", block = false, for = "unix" },
]

# 图像文件 - 使用系统默认查看器
open = [{ run = 'xdg-open "$1"', desc = "系统默认打开", for = "linux" }]

# 视频文件 - 使用 mpv 播放器
play = [{ run = 'mpv "$1"', desc = "MPV 播放", block = false, for = "unix" }]

# PDF文件 - 使用 zathura 或系统默认
read = [
    { run = 'zathura "$1"', desc = "Zathura 阅读", block = false, for = "unix" },
    { run = 'xdg-open "$1"', desc = "系统默认打开", for = "linux" },
]

# 压缩文件 - 解压到当前目录
extract = [{ run = 'unar "$1"', desc = "解压文件", for = "unix" }]

[open]
# 文件关联规则 - 智能匹配
rules = [
    # 文本文件
    { name = "*/", use = ["edit", "open", "reveal"] },
    { mime = "text/*", use = ["edit", "reveal"] },
    { mime = "application/json", use = ["edit", "reveal"] },
    { mime = "*/xml", use = ["edit", "reveal"] },
    { mime = "application/javascript", use = ["edit", "reveal"] },

    # 图像文件
    { mime = "image/*", use = ["open", "reveal"] },

    # 视频和音频
    { mime = "video/*", use = ["play", "reveal"] },
    { mime = "audio/*", use = ["play", "reveal"] },

    # PDF 和文档
    { mime = "application/pdf", use = ["read", "reveal"] },

    # 压缩文件
    { mime = "application/*zip", use = ["extract", "reveal"] },
    { mime = "application/x-tar", use = ["extract", "reveal"] },
    { mime = "application/x-bzip*", use = ["extract", "reveal"] },
    { mime = "application/x-7z*", use = ["extract", "reveal"] },

    # 可执行文件
    { mime = "application/x-executable", use = ["open", "reveal"] },

    # 默认规则
    { name = "*", use = ["open", "reveal"] },
]

[tasks]
# 任务设置 - 优化并发性能
micro_workers = 10
macro_workers = 25
bizarre_retry = 5

[plugin]
# 插件配置目录
prepend_preloaders = [
    { name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]

[log]
# 日志配置 - 调试和性能监控
enabled = false
